// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jffbkxilrtdnyjmqaidx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZmJreGlscnRkbnlqbXFhaWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Njc3ODMsImV4cCI6MjA1OTM0Mzc4M30.ijVHMbmd91rkJetoreEANfsn2iQg_1oOkvUJshc_B2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);